"""initial schema

Revision ID: da53ea883683
Revises: 
Create Date: 2026-09-11 10:03:14.502382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'da53ea883683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('approx_age', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('identifying_marks', sa.String(), nullable=True),
    sa.Column('sterilization_status', sa.String(), nullable=True),
    sa.Column('vaccination_status', sa.String(), nullable=True),
    sa.Column('usual_latitude', sa.Float(), nullable=True),
    sa.Column('usual_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_type', sa.Enum('NGO', 'VETERINARY_CLINIC', 'ANIMAL_HOSPITAL', 'MUNICIPALITY', 'SHELTER', 'RESCUE_NETWORK', name='organization_type_enum'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'RESCUER', 'VETERINARIAN', 'NGO_ADMIN', 'MUNICIPAL_ADMIN', 'FOSTER', 'SUPER_ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('veterinary_facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.models.types.PointField(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('supports_emergency', sa.Boolean(), nullable=True),
    sa.Column('is_24_hours', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foster_homes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('accepted_species', sa.String(), nullable=True),
    sa.Column('maximum_animal_size', sa.String(), nullable=True),
    sa.Column('medical_care_supported', sa.Boolean(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rescue_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.models.types.PointField(), nullable=True),
    sa.Column('address_text', sa.String(), nullable=True),
    sa.Column('bleeding', sa.Boolean(), nullable=True),
    sa.Column('can_walk', sa.Boolean(), nullable=True),
    sa.Column('conscious', sa.Boolean(), nullable=True),
    sa.Column('vehicle_accident', sa.Boolean(), nullable=True),
    sa.Column('breathing_difficulty', sa.Boolean(), nullable=True),
    sa.Column('triage_score', sa.Integer(), nullable=True),
    sa.Column('triage_priority', sa.Enum('GENERAL', 'MODERATE', 'URGENT', 'CRITICAL', name='rescue_priority_enum'), nullable=True),
    sa.Column('triage_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'TRIAGED', 'SEARCHING_RESPONDER', 'RESPONDER_ASSIGNED', 'RESPONDER_EN_ROUTE', 'ANIMAL_LOCATED', 'RESCUED', 'TRANSPORTING', 'AT_VETERINARY_FACILITY', 'UNDER_TREATMENT', 'RECOVERING', 'FOSTER_CARE', 'READY_FOR_RELEASE', 'READY_FOR_ADOPTION', 'RELEASED', 'ADOPTED', 'CLOSED', 'CANCELLED', 'UNRESOLVED', name='rescue_status_enum'), nullable=True),
    sa.Column('veterinary_facility_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('latitude >= -90.0 AND latitude <= 90.0', name='check_rescue_lat'),
    sa.CheckConstraint('longitude >= -180.0 AND longitude <= 180.0', name='check_rescue_lng'),
    sa.CheckConstraint('triage_score IS NULL OR (triage_score >= 0 AND triage_score <= 100)', name='check_rescue_triage_score'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['veterinary_facility_id'], ['veterinary_facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_cases_case_number'), 'rescue_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_rescue_cases_created_at'), 'rescue_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_rescue_cases_reporter_id'), 'rescue_cases', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_rescue_cases_status'), 'rescue_cases', ['status'], unique=False)
    op.create_table('rescuer_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='rescuer_availability_enum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_location', app.models.types.PointField(), nullable=True),
    sa.Column('vehicle_available', sa.Boolean(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescuer_profiles_availability_status'), 'rescuer_profiles', ['availability_status'], unique=False)
    op.create_index(op.f('ix_rescuer_profiles_user_id'), 'rescuer_profiles', ['user_id'], unique=True)
    op.create_table('animal_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=True),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foster_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=True),
    sa.Column('foster_home_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['foster_home_id'], ['foster_homes.id'], ),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('rescue_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=False),
    sa.Column('rescuer_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'EXPIRED', name='assignment_status_enum'), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('dispatch_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.ForeignKeyConstraint(['rescuer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_assignments_rescuer_id'), 'rescue_assignments', ['rescuer_id'], unique=False)
    op.create_table('rescue_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('REPORTED', 'TRIAGED', 'SEARCHING_RESPONDER', 'RESPONDER_ASSIGNED', 'RESPONDER_EN_ROUTE', 'ANIMAL_LOCATED', 'RESCUED', 'TRANSPORTING', 'AT_VETERINARY_FACILITY', 'UNDER_TREATMENT', 'RECOVERING', 'FOSTER_CARE', 'READY_FOR_RELEASE', 'READY_FOR_ADOPTION', 'RELEASED', 'ADOPTED', 'CLOSED', 'CANCELLED', 'UNRESOLVED', name='rescue_status_enum'), nullable=True),
    sa.Column('new_status', sa.Enum('REPORTED', 'TRIAGED', 'SEARCHING_RESPONDER', 'RESPONDER_ASSIGNED', 'RESPONDER_EN_ROUTE', 'ANIMAL_LOCATED', 'RESCUED', 'TRANSPORTING', 'AT_VETERINARY_FACILITY', 'UNDER_TREATMENT', 'RECOVERING', 'FOSTER_CARE', 'READY_FOR_RELEASE', 'READY_FOR_ADOPTION', 'RELEASED', 'ADOPTED', 'CLOSED', 'CANCELLED', 'UNRESOLVED', name='rescue_status_enum'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rescue_case_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=True),
    sa.Column('veterinarian_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_notes', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('treatment_started_at', sa.DateTime(), nullable=True),
    sa.Column('treatment_completed_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('recovery_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['veterinary_facilities.id'], ),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_cases.id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments')
    op.drop_table('rescue_status_history')
    op.drop_index(op.f('ix_rescue_assignments_rescuer_id'), table_name='rescue_assignments')
    op.drop_table('rescue_assignments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('foster_assignments')
    op.drop_table('animal_images')
    op.drop_index(op.f('ix_rescuer_profiles_user_id'), table_name='rescuer_profiles')
    op.drop_index(op.f('ix_rescuer_profiles_availability_status'), table_name='rescuer_profiles')
    op.drop_table('rescuer_profiles')
    op.drop_index(op.f('ix_rescue_cases_status'), table_name='rescue_cases')
    op.drop_index(op.f('ix_rescue_cases_reporter_id'), table_name='rescue_cases')
    op.drop_index(op.f('ix_rescue_cases_created_at'), table_name='rescue_cases')
    op.drop_index(op.f('ix_rescue_cases_case_number'), table_name='rescue_cases')
    op.drop_table('rescue_cases')
    op.drop_table('foster_homes')
    op.drop_table('veterinary_facilities')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('animals')
    # ### end Alembic commands ###
