from enum import Enum

class UserRole(str, Enum):
    CITIZEN = "CITIZEN"
    RESCUER = "RESCUER"
    VETERINARIAN = "VETERINARIAN"
    NGO_ADMIN = "NGO_ADMIN"
    MUNICIPAL_ADMIN = "MUNICIPAL_ADMIN"
    FOSTER = "FOSTER"
    SUPER_ADMIN = "SUPER_ADMIN"

class OrganizationType(str, Enum):
    NGO = "NGO"
    VETERINARIAN_CLINIC = "VETERINARY_CLINIC"
    ANIMAL_HOSPITAL = "ANIMAL_HOSPITAL"
    MUNICIPALITY = "MUNICIPALITY"
    SHELTER = "SHELTER"
    RESCUE_NETWORK = "RESCUE_NETWORK"

class RescuePriority(str, Enum):
    GENERAL = "GENERAL"
    MODERATE = "MODERATE"
    URGENT = "URGENT"
    CRITICAL = "CRITICAL"

class RescueStatus(str, Enum):
    REPORTED = "REPORTED"
    TRIAGED = "TRIAGED"
    SEARCHING_RESPONDER = "SEARCHING_RESPONDER"
    RESPONDER_ASSIGNED = "RESPONDER_ASSIGNED"
    RESPONDER_EN_ROUTE = "RESPONDER_EN_ROUTE"
    ANIMAL_LOCATED = "ANIMAL_LOCATED"
    RESCUED = "RESCUED"
    TRANSPORTING = "TRANSPORTING"
    AT_VETERINARY_FACILITY = "AT_VETERINARY_FACILITY"
    UNDER_TREATMENT = "UNDER_TREATMENT"
    RECOVERING = "RECOVERING"
    FOSTER_CARE = "FOSTER_CARE"
    READY_FOR_RELEASE = "READY_FOR_RELEASE"
    READY_FOR_ADOPTION = "READY_FOR_ADOPTION"
    RELEASED = "RELEASED"
    ADOPTED = "ADOPTED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    UNRESOLVED = "UNRESOLVED"

class RescuerAvailability(str, Enum):
    AVAILABLE = "AVAILABLE"
    BUSY = "BUSY"
    OFFLINE = "OFFLINE"

class AssignmentStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"
